import SpaceBlueBaskMessengerBag from "../images/backpacks/messengerBag/Space-Blue-Bask-Messenger-Bag.png";
import TerracottaRedBaskMessengerBag from "../images/backpacks/messengerBag/Terracotta-Red-Bask-Messenger-Bag.png";
import WalnutBrownBaskMessengerBag from "../images/backpacks/messengerBag/Walnut-Brown-Bask-Messenger-Bag.png";
import NaturalWhiteMustardTrailWeekender from "../images/backpacks/trailWeekender/Natural-White-Mustard-Trail-Weekender.png";
import NaturalWhiteOliveTrailWeekender from "../images/backpacks/trailWeekender/Natural-White-Olive-Trail-Weekender.png";
import BlueIdyllTote from "../images/backpacks/toteBag/Blue-Idyll-Tote.png";
import GreenIdyllTote from "../images/backpacks/toteBag/Green-Idyll-Tote.png";
import WhiteIdyllTote from "../images/backpacks/toteBag/White-Idyll-Tote.png";
import KhakiBeigeOdysseyBackpack from "../images/backpacks/odysseyBackpack/Khaki-Beige-Odyssey-Backpack.png";
import MintGreenOdysseyBackpack from "../images/backpacks/odysseyBackpack/Mint-Green-Odyssey-Backpack.png";
import TangerineWayBackpack from "../images/backpacks/wayBackpack/Tangerine-Way-Backpack.png";
import PineWayBackpack from "../images/backpacks/wayBackpack/Pine-Way-Backpack.png";
import SlateGrayWayBackpack from "../images/backpacks/wayBackpack/Slate-Gray-Way-Backpack.png";
import SpaceBlueWayBackpack from "../images/backpacks/wayBackpack/Space-Blue-Way-Backpack.png";
import BlueScootBackpack from "../images/backpacks/scootBackpack/Blue-Scoot-Backpack.png";
import GreenScootBackpack from "../images/backpacks/scootBackpack/Green-Scoot-Backpack.png";
import OrangeScootBackpack from "../images/backpacks/scootBackpack/Orange-Scoot-Backpack.png";
import RedScootBackpack from "../images/backpacks/scootBackpack/Red-Scoot-Backpack.png";
import YellowScootBackpack from "../images/backpacks/scootBackpack/Yellow-Scoot-Backpack.png";

export const items = [
  {
    id: 1,
    category: "messengerBag",
    img: SpaceBlueBaskMessengerBag,
    name: "Space Blue Messenger Bag",
    price: 4499,
    desc: "Ultra-modern and sophisticated, the Bask Messenger Bag is designed to shine, offering the best - in form and function. It will hold your laptop, documents, and other work essentials.",
    colour: "Space Blue",
    material: "Leatherite & Polysuede",
    dimensions: "30.4 (H) x 42 (W) x 6.4 (D)cm",
  },
  {
    id: 2,
    category: "messengerBag",
    img: TerracottaRedBaskMessengerBag,
    name: "Terracotta Red Messenger Bag",
    price: 4999,
    desc: "Ultra-modern and sophisticated, the Bask Messenger Bag is designed to shine, offering the best - in form and function. It will hold your laptop, documents, and other work essentials.",
    colour: "Terracotta Red",
    material: "Leatherite & Polysuede",
    dimensions: "30.4 (H) x 42 (W) x 6.4 (D)cm",
  },
  {
    id: 3,
    category: "messengerBag",
    img: WalnutBrownBaskMessengerBag,
    name: "Walnut Brown Messenger Bag",
    price: 4499,
    desc: "Ultra-modern and sophisticated, the Bask Messenger Bag is designed to shine, offering the best - in form and function. It will hold your laptop, documents, and other work essentials.",
    colour: "Walnut Brown",
    material: "Leatherite & Polysuede",
    dimensions: "30.4 (H) x 42 (W) x 6.4 (D)cm",
  },
  {
    id: 4,
    category: "trailWeekender",
    img: NaturalWhiteMustardTrailWeekender,
    name: "White Mustard Trail Weekender",
    price: 6499,
    desc: "Trail Weekender Bag comes with one spacious compartment and just enough smaller pockets that let you pack with carefree abandon and yet maintain organised access. Handcrafted with pure cotton canvas in dual as well as solid colour combinations.",
    material: "Cotton Canvas & Genuine Leather",
    dimensions: "30 (H) x 43 (W) x 17 (D) cm",
  },
  {
    id: 5,
    category: "trailWeekender",
    img: NaturalWhiteOliveTrailWeekender,
    name: "White Olive Trail Weekender",
    price: 5999,
    desc: "Trail Weekender Bag comes with one spacious compartment and just enough smaller pockets that let you pack with carefree abandon and yet maintain organised access. Handcrafted with pure cotton canvas in dual as well as solid colour combinations.",
    material: "Cotton Canvas & Genuine Leather",
    dimensions: "30 (H) x 43 (W) x 17 (D) cm",
  },
  {
    id: 6,
    category: "totebag",
    img: GreenIdyllTote,
    name: "Green Idyll Tote",
    price: 3999,
    desc: "Utopian pick for daily swings to the office, last minute shopping spree or just evening strolls to your favourite go-to places! Structured to gratify the needs of compulsive over-packers, the bag is large in size, hence the perfect choice for just-in-case scenarios.",
    colour: "Green",
    material: "Polyester & Polyfill",
    dimensions: "36 (H) x 41 (W) x 14 (D) cm",
  },
  {
    id: 7,
    category: "totebag",
    img: WhiteIdyllTote,
    name: "White Idyll Tote",
    price: 3499,
    desc: "Utopian pick for daily swings to the office, last minute shopping spree or just evening strolls to your favourite go-to places! Structured to gratify the needs of compulsive over-packers, the bag is large in size, hence the perfect choice for just-in-case scenarios.",
    colour: "White",
    material: "Polyester & Polyfill",
    dimensions: "36 (H) x 41 (W) x 14 (D) cm",
  },
  {
    id: 8,
    category: "totebag",
    img: BlueIdyllTote,
    name: "Blue Idyll Tote",
    price: 3999,
    desc: "Utopian pick for daily swings to the office, last minute shopping spree or just evening strolls to your favourite go-to places! Structured to gratify the needs of compulsive over-packers, the bag is large in size, hence the perfect choice for just-in-case scenarios.",
    colour: "Blue",
    material: "Polyester & Polyfill",
    dimensions: "36 (H) x 41 (W) x 14 (D) cm",
  },
  {
    id: 9,
    category: "odysseyBackpack",
    img: KhakiBeigeOdysseyBackpack,
    name: "Khaki Beige Odyssey Backpack",
    price: 4999,
    desc: "A cleverly designed classic, Odyssey brings modern balance to the familiar backpacks. Crafted from luxurious leather and durable canvas in a minimalist design makes this practical backpack a simple yet statement work bag.",
    colour: "Khaki Beige",
    material: "Cotton Canvas & Leather",
    dimensions: "39 (H) x 30 (W) x 13 (D) cm",
  },
  {
    id: 10,
    category: "odysseyBackpack",
    img: MintGreenOdysseyBackpack,
    name: "Mint Odyssey Backpack",
    price: 4999,
    desc: "A cleverly designed classic, Odyssey brings modern balance to the familiar backpacks. Crafted from luxurious leather and durable canvas in a minimalist design makes this practical backpack a simple yet statement work bag.",
    colour: "Mint Green",
    material: "Cotton Canvas & Leather",
    dimensions: "39 (H) x 30 (W) x 13 (D) cm",
  },
  {
    id: 14,
    category: "scootBackpack",
    img: RedScootBackpack,
    name: "Red Scoot Backpack",
    price: 1199,
    desc: "A fresh twist to the everyday backpack, Scoot is ideal portrayal of fashion amalgamated with function. Its two adjustable premium grade leather straps make it comfortable to carry as a backpack while the leather handle on top lets you hold it as a handbag. ",
    colour: "Red",
    material: "Tarpaulin & Leather",
    dimensions: "23 (H) x 30.5 (W) x 9 (D) cm",
  },
  {
    id: 15,
    category: "scootBackpack",
    img: YellowScootBackpack,
    name: "Yellow Scoot Backpack",
    price: 1199,
    desc: "A fresh twist to the everyday backpack, Scoot is ideal portrayal of fashion amalgamated with function. Its two adjustable premium grade leather straps make it comfortable to carry as a backpack while the leather handle on top lets you hold it as a handbag. ",
    colour: "Yellow",
    material: "Tarpaulin & Leather",
    dimensions: "23 (H) x 30.5 (W) x 9 (D) cm",
  },
  {
    id: 11,
    category: "scootBackpack",
    img: GreenScootBackpack,
    name: "Green Scoot Backpack",
    price: 1199,
    desc: "A fresh twist to the everyday backpack, Scoot is ideal portrayal of fashion amalgamated with function. Its two adjustable premium grade leather straps make it comfortable to carry as a backpack while the leather handle on top lets you hold it as a handbag. ",
    colour: "Green",
    material: "Tarpaulin & Leather",
    dimensions: "23 (H) x 30.5 (W) x 9 (D) cm",
  },

  {
    id: 12,
    category: "scootBackpack",
    img: BlueScootBackpack,
    name: "Blue Scoot Backpack",
    price: 1199,
    desc: "A fresh twist to the everyday backpack, Scoot is ideal portrayal of fashion amalgamated with function. Its two adjustable premium grade leather straps make it comfortable to carry as a backpack while the leather handle on top lets you hold it as a handbag. ",
    colour: "Blue",
    material: "Tarpaulin & Leather",
    dimensions: "23 (H) x 30.5 (W) x 9 (D) cm",
  },
  {
    id: 13,
    category: "scootBackpack",
    img: OrangeScootBackpack,
    name: "Orange Scoot Backpack",
    price: 1199,
    desc: "A fresh twist to the everyday backpack, Scoot is ideal portrayal of fashion amalgamated with function. Its two adjustable premium grade leather straps make it comfortable to carry as a backpack while the leather handle on top lets you hold it as a handbag. ",
    colour: "Orange",
    material: "Tarpaulin & Leather",
    dimensions: "23 (H) x 30.5 (W) x 9 (D) cm",
  },
  {
    id: 16,
    category: "wayBackpack",
    img: TangerineWayBackpack,
    name: "Tangerine Way Backpack",
    price: 2499,
    desc: "Way Backpack is a rendition of the classic low-profile daypack with convenient access and two-way carry styles.",
    colour: "Tangerine",
    material: "Polyester",
    dimensions: "43 (H) x 34 (W) x 15 (D) cm",
  },
  {
    id: 17,
    category: "wayBackpack",
    img: PineWayBackpack,
    name: "Pine Way Backpack",
    price: 2499,
    desc: "Way Backpack is a rendition of the classic low-profile daypack with convenient access and two-way carry styles.",
    colour: "Pine",
    material: "Polyester",
    dimensions: "43 (H) x 34 (W) x 15 (D) cm",
  },
  {
    id: 18,
    category: "wayBackpack",
    img: SlateGrayWayBackpack,
    name: "Slate Gray Way Backpack",
    price: 2499,
    desc: "Way Backpack is a rendition of the classic low-profile daypack with convenient access and two-way carry styles.",
    colour: "Slate Gray",
    material: "Polyester",
    dimensions: "43 (H) x 34 (W) x 15 (D) cm",
  },
  {
    id: 19,
    category: "wayBackpack",
    img: SpaceBlueWayBackpack,
    name: "Space Blue Way Backpack",
    price: 2499,
    desc: "Way Backpack is a rendition of the classic low-profile daypack with convenient access and two-way carry styles.",
    colour: "Space Blue",
    material: "Polyester",
    dimensions: "43 (H) x 34 (W) x 15 (D) cm",
  },
];
